# action.yml

name: 'SSH Config'
description: 'Sets up an SSH agent with the given private key'

inputs:
  ssh-private-key:
    description: 'SSH private key'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Set up SSH key
      env:
        PRIVATE_KEY: ${{ inputs.ssh-private-key }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_ed25519
      shell: bash

    - name: Add GitHub to known hosts
      run: |
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      shell: bash

    - name: Modify SSH config file
      run: |
        echo "Host *" > ~/.ssh/config
        echo "  AddKeysToAgent yes" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
        echo "  IgnoreUnknown UseKeychain" >> ~/.ssh/config
      shell: bash

    - name: Configure Git to use SSH
      run: |
        git config --global url."git@github.com:".insteadOf "https://github.com/"
      shell: bash
