# action.yml

name: 'SSH Config'
description: 'Sets up an SSH agent with the given private key'

inputs:
  ssh-private-key:
    description: 'SSH private key'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Set up SSH key
      env:
        PRIVATE_KEY: ${{ inputs.ssh-private-key }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        ssh-agent sh -c 'ssh-add private_key;'
        rm -f private_key

    - name: Add GitHub to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
        
    - name: Check if SSH config file exists
      run: |
        if [ ! -f ~/.ssh/config ]; then
          touch ~/.ssh/config
        fi
      
    - name: Modify SSH config file
      run: |
        echo "Host *" >> ~/.ssh/config
        echo "  AddKeysToAgent yes" >> ~/.ssh/config
        echo "  IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
        if [ -f ~/.ssh/id_ed25519.pub ]; then
          echo "  IdentityFile ~/.ssh/id_ed25519.pub" >> ~/.ssh/config
        fi
        echo "  IgnoreUnknown UseKeychain" >> ~/.ssh/config
        # Omit 'UseKeychain' line if passphrase not used
        # echo "  UseKeychain yes" >> ~/.ssh/config
        
    - name: Configure SSH agent and Git
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "$PRIVATE_KEY" > private_key
        chmod 600 private_key
        eval "$(ssh-agent -s)"
        ssh-add private_key
        rm -f private_key
        git config --global url."git@github.com:".insteadOf "https://github.com/"
